### ISSUE TITLE
{error, "Incomplete form (missing .)??"}

### ISSUE THREAD

**Issue by WoelkiM** [wattlebirdaz/rclref#6]
When I want to start rclref in cluster mode this error always comes up: {error, "Incomplete form (missing .)??"}
I suspect it is because the dots at the end of the line are missing. 
Example: $(BASEDIR)/_build/dev3/rel/rclref/bin/$(APPNAME) eval 'riak_core_console:member_status([])**.**'

**Comment by WoelkiM** [comment]
To make the bug a little clearer. The error occurs when you want to start under Erlang 23, the system in the multi-node configuration. (According to description)

**Comment by albsch** [comment]
At some point `rebar3 eval` changed (or enforced?) it's format such that the thing to be evaluated is a proper Erlang term.

**Comment by WoelkiM** [comment]
okay thanks for the information. The pull request (#7) should then fulfill the new format.
